### ISSUE TITLE
autodbbackup settings can be altered by anyone with access to ACP

### ISSUE THREAD

**Issue by Sophist-UK** [david63/david63-autodbbackup#3]
IMO the autodbbackup settings should only be accessible by someone with the  "Can backup/restore database" ACL permission.

My phpbb 3.2.1 board distinguishes between **technical support** administrators who maintain the software environment and **board content** administrators who are responsible for everything that board users see.

But despite **NOT** having "Can backup/restore database" permissions, the **board content"" administrators can still e.g. turn off automatic backup.

**Comment by Sophist-UK** [comment]
I thought that the acl was defined in `ext/david63/autodbbackup/acp/auto_db_backup_info.php` where it says `'auth' => 'ext_david63/autodbbackup && acl_a_board'`.

I changed this to `'auth' => 'ext_david63/autodbbackup && acl_a_backup'` expecting this to fix the problem (acl_a_backup being the acl referred to in `/includes/acp/info/acp_database.php'` as controlling whether backup and restore functions appear) but this hasn't made any difference.

So over to someone more knowledgeable about phpbb coding than me for a fix.

**Comment by david63** [comment]
You would have to disable/delete data then change the setting and reinstall to get that to work - just changing it in the file will make no difference

**Comment by Sophist-UK** [comment]
I previously disabled and re-enabled, but it made no difference.

I have disabled, deleted data, re-enabled and that fixed it.

**Comment by Sophist-UK** [comment]
Would you like me to submit a PR?

**Comment by david63** [comment]
No - I'll change it, but thanks
