### ISSUE TITLE
autodbbackup time varies

### ISSUE THREAD

**Issue by Sophist-UK** [david63/david63-autodbbackup#4]
I previously configured autodbbackup to run every 24 hours at 6am. Obviously it only runs when someone accesses the board and triggers the phpbb cron functionality, so I don't expect it to run at exactly 6am.

When I looked at the settings today, the next backup is scheduled for 1:25pm tomorrow, presumably because the first user today was me at 1:25, so it did a backup and then scheduled the next one 24 hours later.

Any chance that we can fix it so that regardless of the time it actually runs, it calculates the next run time as it it had run exactly on time?

**Comment by david63** [comment]
That is in the next version - but it will never be guaranteed to run exactly on time

**Comment by Sophist-UK** [comment]
I don't see it in your GitHub code. But it doesn't look to difficult to code, so would you like me to give it a go and submit a PR?

**Comment by david63** [comment]
Thanks but it is already coded - just not uploaded it yet

**Comment by Galixte** [comment]
Hi @david63,

when it will be uploaded on the repository?
